// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igrwsesbqwrzxnkydxhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncndzZXNicXdyenhua3lkeGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTM3MTEsImV4cCI6MjA2OTcyOTcxMX0.qQ5ecBemaxpTpBlyG7_TPNZyzUsAEcL5STWd0W98n60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});